# API-first development with swagger
# This file will be used at compile time to generate Spring-MVC endpoint stubs using swagger-codegen
swagger: "2.2.3"
info:
  title: "artemis"
  version: 0.0.1
paths: {}