version: '2'
services:
    artemis-app:
        image: artemis
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://artemis-postgresql:5432/artemis
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    artemis-postgresql:
        extends:
            file: postgresql.yml
            service: artemis-postgresql
